<?xml version="1.0" encoding="utf-8"?><Database Name="BlogDB" Class="BlogDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\BlogDB.mdf;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="BlogDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Ustawienia" Member="Ustawienias">
    <Type Name="Ustawienia">
      <Column Name="grupa" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="nazwa" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="wartosc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Tagi" Member="Tagis">
    <Type Name="Tagi">
      <Column Name="id_post" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="keywords" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Post_Tagi" Member="Post" ThisKey="id_post" OtherKey="id" Type="Post" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Post" Member="Posts">
    <Type Name="Post">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tytul" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="tresc" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="data_dodania" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="data_modyfikacji" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Post_Tagi" Member="Tagi" ThisKey="id" OtherKey="id_post" Type="Tagi" Cardinality="One" />
      <Association Name="Post_Komentarze" Member="Komentarzes" ThisKey="id" OtherKey="id_posta" Type="Komentarze" />
    </Type>
  </Table>
  <Table Name="dbo.Komentarze" Member="Komentarzes">
    <Type Name="Komentarze">
      <Column Name="id_komentarza" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="id_posta" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tresc_komentarza" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="autor_komentarza" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="data_dodania_komentarza" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Post_Komentarze" Member="Post" ThisKey="id_posta" OtherKey="id" Type="Post" IsForeignKey="true" />
    </Type>
  </Table>
</Database>